# Generated by Django 4.2.1 on 2023-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Adress', models.CharField(max_length=255)),
                ('Product', models.CharField(choices=[('symotedz Analytics', 'Symotedz Analytics'), ('Symotedz bulk server', 'Symotedz bulk server'), ('Symoted appointment booking system', 'Symotedz appointment booking system'), ('Symotedz ISP system', 'Symotedz isp system'), ('Symotedz HR,Payroll & Accounting System', 'Symotedz HR,Payroll & Accounting system')], max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('enquiry', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
